-- -- after/plugin/nvim-dap.lua
-- local dap = require('dap')
--
-- -- You can configure DAP adapters and configurations here
-- dap.adapters.python = {
--   type = 'executable';
--   command = 'python';
--   args = { '-m', 'debugpy.adapter' };
-- }
--
-- dap.configurations.python = {
--   {
--     type = 'python';
--     request = 'launch';
--     name = "Launch file";
--     program = "${file}";
--     pythonPath = function()
--       return 'python'
--     end;
--   },
-- }
--
